### ISSUE TITLE
vite-plugin-commonjs

### ISSUE THREAD

**Issue by caoxiemeihao** [youngleish/keep-love#11]
- [x] 加入 `dynamic require` 能力，与 `vite-require` 对齐(v0.5.0)
- [x] test 重构(v0.5.0)
- [x] sync v0.5.0

**Comment by caoxiemeihao** [comment]
https://github.com/vite-plugin/vite-plugin-commonjs/tree/v0.5.0

**Comment by youngleish** [comment]
done
- [x] 加入 dynamic require 能力，与 vite-require 对齐(v0.5.0)
- [x]  test 重构(v0.5.0)
