### ISSUE TITLE
vite-require

### ISSUE THREAD

**Issue by caoxiemeihao** [youngleish/keep-love#16]
- [x] 优化代码，对齐 vite-plugin-commonjs
  1. 代码注释
  2. `options` 调整
- [x] https://github.com/vite-plugin/vite-plugin-dynamic-import/issues/16
- [x] https://github.com/vite-plugin/vite-plugin-dynamic-import/commit/a52709322b00f524b98979e9cb4de34af1b3fb08

**Comment by caoxiemeihao** [comment]
遗漏功能:  
```ts
  dynamic?:
  | 'dynamic'
  // e.g. require(`@/foo/bar.js`) 
  | 'Literal'
```
https://github.com/vite-plugin/vite-plugin-commonjs/blob/b75afd4f954b297cfd5b3b3cb98c78bdcc0203cb/src/analyze.ts#L21

---

```ts
      // skip itself
      files = files.filter(f => path.join(path.dirname(id), f) !== id)
      // execute the dynamic.onFiles
      options.dynamic?.onFiles && (files = options.dynamic?.onFiles(files, id) || files)
```

https://github.com/vite-plugin/vite-plugin-commonjs/blob/b75afd4f954b297cfd5b3b3cb98c78bdcc0203cb/src/dynamic-require.ts#L63

---

```diff
- filter?: (id: string) => false | void
+ filter?: (id: string) => false | undefined
```

https://github.com/vite-plugin/vite-require/blob/1b023c617d0073deb9604c7122cfed8e122adfeb/src/index.ts#L19

**Comment by youngleish** [comment]
🥺
