### ISSUE TITLE
Big project

### ISSUE THREAD

**Issue by caoxiemeihao** [youngleish/keep-love#17]
- [x] 升级依赖，**vite要升级到最新的版本 ^3.0.0-beta.5**
- [x] 改写 electron/main.ts 下的代码

```diff,ts
- // 🚧 Use ['ENV_NAME'] avoid vite:define plugin
- const url = `http://${process.env['VITE_DEV_SERVER_HOST']}:${process.env['VITE_DEV_SERVER_PORT']}`
+ const url = `http://${process.env.VITE_DEV_SERVER_HOST}:${process.env.VITE_DEV_SERVER_PORT}`
```

因为 Vite 内部判断了 `build.lib` 的情况；我们项目的 main.ts 刚好用的 `build.lib` 模式。
https://github.com/vitejs/vite/commit/908c9e4cdd2cceb0f01495e38066ffe33c21ddb8

**Comment by youngleish** [comment]
done
