### ISSUE TITLE
electron-vite-vue

### ISSUE THREAD

**Issue by caoxiemeihao** [youngleish/keep-love#37]
- [x] 依赖升级
- [x] 去掉 [renderBuiltUrl](https://github.com/electron-vite/electron-vite-vue/blob/05a9c08770f0f9e041f0e76ee9d45055a58c2aaa/vite.config.ts#L68-L121) 插件，已在 `vite-plugin-electron` 中集成

**Comment by youngleish** [comment]
🙃
